## Numpy
---

### Present notebook discuss the majorly used functions of the _numpy_ (version 1.18.5)

* Install the numpy with pip using following command

```!pip install numpy```

* Load the library as ```np``` after installation.

In [1]:
# Loading library
import numpy as np

# This will print entire output of the cell
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
# List objects
row1 = [1,2,3]
row2 = [4,5,6]
row3 = [7,8,9]

### 1. ```np.array()```
* Typecasting lists to numpy-array using ```np.array()```

In [3]:
# Typecasting all 3 lists together
nupyArray = np.array([row1, row2, row3])
nupyArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 2. ```np.arange()```
* Generates linear arrays
* ```np.arange()``` takes two argumnets (Start & Stop) and step-difference is optional

In [4]:
# Making linear array from 1 to 18 (inclusive)
largeNpArray = np.arange(1, 19, 2) # 2 is the step difference
largeNpArray

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17])

### 3. ```np.zeros()``` or ```np.ones()``` 
* Generates arrays of zeros or ones
* For making multi-dimensional arrays pass the tuple having dimensions. 
* They creates float objects not rather than integers

In [5]:
# Making linear array of 0s
allZeros = np.zeros(10)
allZeros

# Making 2-D array of 1s
allOnes = np.ones((3,3))
allOnes

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 4. ```np.linspace()```
* Generates linear arrays having user-defined differencing
* Similar to ```np.arange()```, accepts starts and stops
* Inclusive of start & end points

In [6]:
# Making a linear array from 1-2 with 6 elements
linArray = np.linspace(1,2,6)
linArray

array([1. , 1.2, 1.4, 1.6, 1.8, 2. ])

### 5. ```np.random.randint()```
* ```np.random``` class has many methods, out of which ```np.random.randint()``` generates random integers between user-defined ranges
* The start position is inclusive and the end position is exclusive
* Multi-dimensional array can also be generated by passing tuple as argument
* To generate identical random numbers, set the ```np.random.seed()``` equal to desired number

In [7]:
# Genrating random 2-D matrix with seed
np.random.seed(123) # Generates same numbers everytime
randomArray = np.random.randint(1,10,(3,3))
randomArray

array([[3, 3, 7],
       [2, 4, 7],
       [2, 1, 2]])

### 6. Operations
* ```array.max()```, for finding maximum value in array
* ```array.min()```, for finding minimum value in array
* ```array.mean()```, for finding mean of the array values

In [8]:
# Applying, max(), min() and mean() on previously created randomArray
randomArray.max()
randomArray.min()
randomArray.mean()

7

1

3.4444444444444446

### 7. Index of the elements
* ```array.argmax()```, for finding the _index_ maximum value in array
* ```array.argmin()```,for finding the _index_ minimum value in array

In [9]:
# Applying, argmax(), argmin() on previously created randomArray
randomArray.argmax()
randomArray.argmin()

2

7

### 8. Reshaping
* ```reshape()```, is the method of the nummpy-array object
* It accepts two arguments namely _raw_ & _column_
* It only works with even distributions

In [10]:
# Using previously made linArray
linArray_reshaped = linArray.reshape(2,3)
linArray_reshaped

array([[1. , 1.2, 1.4],
       [1.6, 1.8, 2. ]])

### 9. Numpy-Array indexing & slicing
* For elemental indexing use; ```array[row,column]```
* For linear array slicing use; ```array[:,column]``` or ```array[row,:]```
* For multi-dimensional array slicing use; ```array[Start:Stop,Start:Stop]```

In [11]:
# Making array using np.arange()
array = np.arange(1,21,1).reshape(4,5)
array

# Elemental Indexing
array[2,4]

# Linear Array Slicing 
array[3,:]

# Multi-dimensional Array Slicing
array[1:4,3:5] # end position is exclusive

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

15

array([16, 17, 18, 19, 20])

array([[ 9, 10],
       [14, 15],
       [19, 20]])

### 10. Boolean indexing & slicing
* It returns boolean array i.e. True/False, which can be used to subset the array

In [12]:
# Using previously made array
array

# generating boolean-array
boolArray = array < 10
boolArray

# Subseting with boolArray
subArray = array[boolArray].reshape(3,3)
subArray

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

---